# Generated by Django 5.0.3 on 2024-05-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='first_name',
            new_name='emp_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employees',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='hourly_pay',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
